#!/usr/bin/env bash
# check-tdd_test.sh - black-box tests for check-tdd.sh.
#
# Each case sets up a throwaway git repo with a base commit and a
# head commit, then invokes check-tdd.sh with BASE_SHA / HEAD_SHA
# env vars. Asserts on exit code and (optionally) stdout substring.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
check="$script_dir/check-tdd.sh"

failed=0
pass=0

run_case() {
  local name="$1"; shift
  local want_exit="$1"; shift
  local want_stdout_match="$1"; shift  # may be empty
  local setup="$1"; shift               # bash function name

  tmp=$(mktemp -d)
  pushd "$tmp" >/dev/null

  git init -q
  git config user.email t@t
  git config user.name t

  # Base commit: empty go.mod so the repo is a valid module root.
  cat > go.mod <<EOF
module example.com/x

go 1.22
EOF
  git add go.mod
  git commit -q -m base
  base=$(git rev-parse HEAD)

  # Setup function builds the head state.
  "$setup"
  git add -A
  git commit -q -m head
  head=$(git rev-parse HEAD)

  out=$(BASE_SHA="$base" HEAD_SHA="$head" BODY="${BODY:-}" "$check" 2>&1) && got_exit=0 || got_exit=$?

  if [ "$got_exit" != "$want_exit" ]; then
    echo "FAIL $name: exit=$got_exit want $want_exit"
    echo "  output: $out"
    failed=$((failed + 1))
  elif [ -n "$want_stdout_match" ] && ! echo "$out" | grep -q "$want_stdout_match"; then
    echo "FAIL $name: stdout missing '$want_stdout_match'"
    echo "  output: $out"
    failed=$((failed + 1))
  else
    pass=$((pass + 1))
    echo "PASS $name"
  fi

  popd >/dev/null
  rm -rf "$tmp"
  unset BODY
}

# --- cases ---

case_prod_only_fails() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
}

case_prod_with_test_passes() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
  cat > internal/foo/foo_test.go <<EOF
package foo

import "testing"

func TestFoo(t *testing.T) {
  if Foo() != 42 { t.Fatal("nope") }
}
EOF
}

case_test_only_passes() {
  mkdir -p internal/foo
  cat > internal/foo/foo_test.go <<EOF
package foo

import "testing"

func TestSomething(t *testing.T) {}
EOF
}

case_generated_skipped() {
  mkdir -p internal/gen
  cat > internal/gen/gen.go <<EOF
// Code generated by something; DO NOT EDIT.

package gen

const Magic = 42
EOF
}

case_docs_category_passes() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
  BODY=$(cat <<EOM
some body
\`\`\`release-notes
[DOCS] notes
\`\`\`
EOM
)
  export BODY
}

case_chore_category_passes() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
  BODY=$(cat <<EOM
\`\`\`release-notes
[CHORE] tidy
\`\`\`
EOM
)
  export BODY
}

case_feature_category_still_requires_test() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
  BODY=$(cat <<EOM
\`\`\`release-notes
[FEATURE] new thing
\`\`\`
EOM
)
  export BODY
}

case_cmd_test_in_internal_passes() {
  # cmd/regatta/main.go shipped with internal/foo/foo_test.go - allowed
  # because the check walks up dirs and tolerates a test anywhere in
  # the same top-level subtree. We deliberately allow this looseness:
  # the gate is a forcing function, not a perfect map.
  mkdir -p cmd/regatta internal/foo
  cat > cmd/regatta/main.go <<EOF
package main

func main() {}
EOF
  cat > internal/foo/foo_test.go <<EOF
package foo

import "testing"

func TestX(t *testing.T) {}
EOF
}

run_case prod_only_fails                       1 "without a matching" case_prod_only_fails
run_case prod_with_test_passes                 0 "every production"   case_prod_with_test_passes
run_case test_only_passes                      0 "no production"      case_test_only_passes
run_case generated_skipped                     0 "no production"      case_generated_skipped
run_case docs_category_passes                  0 "category"           case_docs_category_passes
run_case chore_category_passes                 0 "category"           case_chore_category_passes
run_case feature_category_still_requires_test  1 "without a matching" case_feature_category_still_requires_test
# This last case fails because the prod file's top-level dir is cmd/
# and the test file's is internal/. The walk-up logic only matches
# within a shared ancestor; cmd/ and internal/ have no shared ancestor
# below the repo root. Expected: FAIL.
run_case prod_cmd_test_internal_fails          1 "without a matching" case_cmd_test_in_internal_passes

echo
echo "summary: $pass passed, $failed failed"
exit $failed
