#!/usr/bin/env bash
# check-tdd_test.sh - black-box tests for check-tdd.sh.
#
# Each case sets up a throwaway git repo with a base commit and a
# head commit, then invokes check-tdd.sh with BASE_SHA / HEAD_SHA
# env vars. Asserts on exit code and (optionally) stdout substring.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
check="$script_dir/check-tdd.sh"

failed=0
pass=0

run_case() {
  local name="$1"; shift
  local want_exit="$1"; shift
  local want_stdout_match="$1"; shift  # may be empty
  local setup="$1"; shift               # bash function name

  tmp=$(mktemp -d)
  pushd "$tmp" >/dev/null

  git init -q -b main
  git config user.email t@t
  git config user.name t

  # Base commit: empty go.mod so the repo is a valid module root.
  cat > go.mod <<EOF
module example.com/x

go 1.22
EOF
  git add go.mod
  git commit -q -m base
  base=$(git rev-parse HEAD)
  # Pin origin/main at base so the script's live merge-base resolution
  # has a fixed anchor; the feature branch then diverges below.
  git update-ref refs/remotes/origin/main HEAD
  git checkout -q -b feature

  # Setup function builds the head state.
  "$setup"
  git add -A
  git commit -q -m head
  head=$(git rev-parse HEAD)

  out=$(BASE_SHA="$base" HEAD_SHA="$head" BODY="${BODY:-}" "$check" 2>&1) && got_exit=0 || got_exit=$?

  if [ "$got_exit" != "$want_exit" ]; then
    echo "FAIL $name: exit=$got_exit want $want_exit"
    echo "  output: $out"
    failed=$((failed + 1))
  elif [ -n "$want_stdout_match" ] && ! echo "$out" | grep -q "$want_stdout_match"; then
    echo "FAIL $name: stdout missing '$want_stdout_match'"
    echo "  output: $out"
    failed=$((failed + 1))
  else
    pass=$((pass + 1))
    echo "PASS $name"
  fi

  popd >/dev/null
  rm -rf "$tmp"
  unset BODY
}

case_prod_only_fails() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
}

case_prod_with_test_passes() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
  cat > internal/foo/foo_test.go <<EOF
package foo

import "testing"

func TestFoo(t *testing.T) {
  if Foo() != 42 { t.Fatal("nope") }
}
EOF
}

case_test_only_passes() {
  mkdir -p internal/foo
  cat > internal/foo/foo_test.go <<EOF
package foo

import "testing"

func TestSomething(t *testing.T) {}
EOF
}

case_generated_skipped() {
  mkdir -p internal/gen
  cat > internal/gen/gen.go <<EOF
// Code generated by something; DO NOT EDIT.

package gen

const Magic = 42
EOF
}

case_docs_category_passes() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
  BODY=$(cat <<EOM
some body
\`\`\`release-notes
[DOCS] notes
\`\`\`
EOM
)
  export BODY
}

case_chore_category_passes() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
  BODY=$(cat <<EOM
\`\`\`release-notes
[CHORE] tidy
\`\`\`
EOM
)
  export BODY
}

case_feature_category_still_requires_test() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
  BODY=$(cat <<EOM
\`\`\`release-notes
[FEATURE] new thing
\`\`\`
EOM
)
  export BODY
}

case_cmd_test_in_internal_passes() {
  # cmd/regatta/main.go shipped with internal/foo/foo_test.go - allowed
  # because the check walks up dirs and tolerates a test anywhere in
  # the same top-level subtree. We deliberately allow this looseness:
  # the gate is a forcing function, not a perfect map.
  mkdir -p cmd/regatta internal/foo
  cat > cmd/regatta/main.go <<EOF
package main

func main() {}
EOF
  cat > internal/foo/foo_test.go <<EOF
package foo

import "testing"

func TestX(t *testing.T) {}
EOF
}

case_empty_test_file_does_not_satisfy() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
  cat > internal/foo/foo_test.go <<EOF
package foo
EOF
}

case_test_with_benchmark_satisfies() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
  cat > internal/foo/foo_test.go <<EOF
package foo

import "testing"

func BenchmarkFoo(b *testing.B) {
  for i := 0; i < b.N; i++ { _ = Foo() }
}
EOF
}

case_testdata_go_skipped() {
  mkdir -p internal/foo/testdata
  cat > internal/foo/testdata/fixture.go <<EOF
package fixture

const Sample = "hi"
EOF
}

# c1 positive: cmd/regatta/wire.go adds Wire(); the only test lives in
# internal/foo/foo_test.go but mentions the new symbol Wire. Pre-fix
# this fails (top-level subtrees cmd/ vs internal/ share no ancestor
# below repo root); post-fix the cross-package symbol mention satisfies
# the gate. Models the BUG-1055 pattern (wire_prwatch.go + cross-pkg
# unit test on the wired component).
case_cross_pkg_symbol_match_passes() {
  mkdir -p cmd/regatta internal/foo
  cat > cmd/regatta/wire.go <<EOF
package main

func Wire() int { return 1 }
EOF
  cat > internal/foo/foo_test.go <<EOF
package foo

import "testing"

func TestWireIntegration(t *testing.T) {
  // exercises Wire through the wired-up code path
  _ = "Wire"
}
EOF
}

# c1 negative: prod adds Foo, the test in the diff mentions only Bar.
# Even with the symbol-match fallback, zero mentions = gate fails.
case_cross_pkg_symbol_mismatch_fails() {
  mkdir -p cmd/regatta internal/foo
  cat > cmd/regatta/wire.go <<EOF
package main

func Foo() int { return 1 }
EOF
  cat > internal/foo/foo_test.go <<EOF
package foo

import "testing"

func TestBar(t *testing.T) {
  _ = "Bar"
}
EOF
}

case_deletion_only_passes() {
  mkdir -p internal/foo
  cat > internal/foo/foo.go <<EOF
package foo

func Foo() int { return 42 }
EOF
  git add internal/foo/foo.go
  git commit -q -m intermediate --allow-empty
  base=$(git rev-parse HEAD~1)
  cat > internal/foo/foo.go <<EOF
package foo
EOF
}

# Stale BASE_SHA: the env var points at an older origin/main than the
# current merge-base. Simulates the GitHub Actions failure mode where
# main moved (an unrelated PR landed a prod file) between PR open and
# pr-lint re-run. The script must prefer the live merge-base over the
# stale env input so the unrelated file does not appear in the diff
# window. Implemented as a custom test path because run_case wraps the
# standard base/head selection.
run_stale_base_case() {
  local name="stale_base_sha_ignores_unrelated_main_move"
  local want_exit=0
  local want_stdout_match="no production"

  tmp=$(mktemp -d)
  pushd "$tmp" >/dev/null

  git init -q -b main
  git config user.email t@t
  git config user.name t

  cat > go.mod <<EOF
module example.com/x

go 1.22
EOF
  git add go.mod
  git commit -q -m base
  stale_base=$(git rev-parse HEAD)

  # Simulate an unrelated PR landing prod code on main AFTER stale_base
  # was snapshotted (this is the commit that pollutes the stale diff
  # window in the real failure mode).
  mkdir -p cmd/regatta
  cat > cmd/regatta/serve.go <<EOF
package main

func Serve() int { return 1 }
EOF
  git add cmd/regatta/serve.go
  git commit -q -m unrelated-main-move

  # origin/main is now at the post-move commit; the feature branch
  # forks from here with a docs-only diff.
  git update-ref refs/remotes/origin/main HEAD
  git checkout -q -b feature
  mkdir -p docs
  echo "spec body" > docs/spec.md
  git add docs/spec.md
  git commit -q -m spec-only
  head=$(git rev-parse HEAD)

  # Drive the script with the STALE base (pre-move). Without the fix
  # the diff window includes cmd/regatta/serve.go and trips the gate.
  out=$(BASE_SHA="$stale_base" HEAD_SHA="$head" BODY="" "$check" 2>&1) && got_exit=0 || got_exit=$?

  if [ "$got_exit" != "$want_exit" ]; then
    echo "FAIL $name: exit=$got_exit want $want_exit"
    echo "  output: $out"
    failed=$((failed + 1))
  elif [ -n "$want_stdout_match" ] && ! echo "$out" | grep -q "$want_stdout_match"; then
    echo "FAIL $name: stdout missing '$want_stdout_match'"
    echo "  output: $out"
    failed=$((failed + 1))
  else
    pass=$((pass + 1))
    echo "PASS $name"
  fi

  popd >/dev/null
  rm -rf "$tmp"
}

run_case prod_only_fails                        1 "without a matching" case_prod_only_fails
run_case prod_with_test_passes                  0 "every production"   case_prod_with_test_passes
run_case test_only_passes                       0 "no production"      case_test_only_passes
run_case generated_skipped                      0 "no production"      case_generated_skipped
run_case docs_category_passes                   0 "category"           case_docs_category_passes
run_case chore_category_passes                  0 "category"           case_chore_category_passes
run_case feature_category_still_requires_test   1 "without a matching" case_feature_category_still_requires_test
run_case empty_test_file_does_not_satisfy       1 "without a matching" case_empty_test_file_does_not_satisfy
run_case test_with_benchmark_satisfies          0 "every production"   case_test_with_benchmark_satisfies
# This last case fails because the prod file's top-level dir is cmd/
# and the test file's is internal/. The walk-up logic only matches
# within a shared ancestor; cmd/ and internal/ have no shared ancestor
# below the repo root. Expected: FAIL.
run_case prod_cmd_test_internal_fails          1 "without a matching" case_cmd_test_in_internal_passes
run_case testdata_go_skipped                    0 "no production"      case_testdata_go_skipped
run_case cross_pkg_symbol_match_passes          0 "every production"   case_cross_pkg_symbol_match_passes
run_case cross_pkg_symbol_mismatch_fails        1 "without a matching" case_cross_pkg_symbol_mismatch_fails
run_stale_base_case

echo
echo "summary: $pass passed, $failed failed"
exit $failed
