#!/usr/bin/env bash
# gen-specs-readme_test.sh - assertions for scripts/gen-specs-readme.sh.
#
# Tests run against an isolated fixture directory under scripts/testdata/
# specs-index/, then point the generator at that dir via the SPECS_DIR env.
# Real repo state stays untouched.

set -uo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
GEN="$REPO_ROOT/scripts/gen-specs-readme.sh"
FIXTURES="$SCRIPT_DIR/testdata/specs-index"

passes=0
fails=0
failed_names=()

ok()   { passes=$((passes + 1)); echo "ok   $1"; }
fail() { fails=$((fails + 1)); failed_names+=("$1"); echo "FAIL $1: $2"; }

setup_workdir() {
  # Copy fixture corpus into a fresh tmpdir; emit absolute path on stdout.
  local tmp
  tmp=$(mktemp -d)
  cp -R "$FIXTURES"/. "$tmp"/
  echo "$tmp"
}

# TestGenSpecsReadme_DeterministicOnSameInput
case_deterministic() {
  local name="deterministic on same input"
  local dir
  dir=$(setup_workdir)
  bash "$GEN" --specs-dir "$dir" --out "$dir/README.md" >/dev/null 2>&1
  local first
  first=$(cat "$dir/README.md")
  bash "$GEN" --specs-dir "$dir" --out "$dir/README.md" >/dev/null 2>&1
  local second
  second=$(cat "$dir/README.md")
  rm -rf "$dir"
  if [ "$first" = "$second" ]; then ok "$name"; else fail "$name" "two runs diverged"; fi
}

# TestGenSpecsReadme_IncludesAllSpecs
case_includes_all_specs() {
  local name="includes all spec files"
  local dir
  dir=$(setup_workdir)
  bash "$GEN" --specs-dir "$dir" --out "$dir/README.md" >/dev/null 2>&1
  local missing=""
  for f in "$dir"/*.md; do
    local base
    base=$(basename "$f")
    [ "$base" = "README.md" ] && continue
    # Match either escaped or plain link target.
    if ! grep -qF "($base)" "$dir/README.md" && ! grep -qF "(./$base)" "$dir/README.md"; then
      missing="${missing}${base} "
    fi
  done
  rm -rf "$dir"
  if [ -z "$missing" ]; then ok "$name"; else fail "$name" "missing: $missing"; fi
}

# TestGenSpecsReadme_SkipsREADMEItself
case_skips_readme() {
  local name="skips README.md itself"
  local dir
  dir=$(setup_workdir)
  # Pre-seed a stale README that, if scanned, would self-include.
  echo "# Old README" > "$dir/README.md"
  bash "$GEN" --specs-dir "$dir" --out "$dir/README.md" >/dev/null 2>&1
  local hits
  hits=$(grep -cE '\(README\.md\)|\(\./README\.md\)' "$dir/README.md" || true)
  rm -rf "$dir"
  if [ "$hits" -eq 0 ]; then ok "$name"; else fail "$name" "README listed itself ($hits hits)"; fi
}

# TestGenSpecsReadme_FrontmatterStatusGroups
case_status_groups() {
  local name="frontmatter status groups specs by section"
  local dir
  dir=$(setup_workdir)
  bash "$GEN" --specs-dir "$dir" --out "$dir/README.md" >/dev/null 2>&1
  local content
  content=$(cat "$dir/README.md")
  local fail_reason=""
  # Section headings must exist.
  echo "$content" | grep -qE '^## Active' || fail_reason="${fail_reason}no Active heading; "
  echo "$content" | grep -qE '^## Shipped' || fail_reason="${fail_reason}no Shipped heading; "
  echo "$content" | grep -qE '^## Archived' || fail_reason="${fail_reason}no Archived heading; "
  # Each fixture must land in the right section. Use awk to slice by H2.
  active_block=$(echo "$content" | awk '/^## Active/{p=1;next} /^## /{p=0} p')
  shipped_block=$(echo "$content" | awk '/^## Shipped/{p=1;next} /^## /{p=0} p')
  archived_block=$(echo "$content" | awk '/^## Archived/{p=1;next} /^## /{p=0} p')
  echo "$active_block" | grep -qF 'spec-frontmatter-active.md' || fail_reason="${fail_reason}active fixture not in Active; "
  echo "$shipped_block" | grep -qF 'spec-frontmatter-shipped.md' || fail_reason="${fail_reason}shipped fixture not in Shipped; "
  echo "$archived_block" | grep -qF 'spec-frontmatter-archived.md' || fail_reason="${fail_reason}archived fixture not in Archived; "
  # Unmarked specs default to Active.
  echo "$active_block" | grep -qF 'spec-plain.md' || fail_reason="${fail_reason}plain spec not defaulted to Active; "
  rm -rf "$dir"
  if [ -z "$fail_reason" ]; then ok "$name"; else fail "$name" "$fail_reason"; fi
}

# TestGenSpecsReadme_FrontmatterTitleOverridesH1
case_frontmatter_title_overrides() {
  local name="frontmatter title wins over H1"
  local dir
  dir=$(setup_workdir)
  bash "$GEN" --specs-dir "$dir" --out "$dir/README.md" >/dev/null 2>&1
  local content
  content=$(cat "$dir/README.md")
  rm -rf "$dir"
  if echo "$content" | grep -qF "Active Spec — frontmatter override"; then
    ok "$name"
  else
    fail "$name" "frontmatter title not used"
  fi
}

# TestGenSpecsReadme_AutoGeneratedBanner
case_banner_present() {
  local name="output carries AUTO-GENERATED banner"
  local dir
  dir=$(setup_workdir)
  bash "$GEN" --specs-dir "$dir" --out "$dir/README.md" >/dev/null 2>&1
  local has_banner
  has_banner=$(head -3 "$dir/README.md" | grep -c 'AUTO-GENERATED' || true)
  rm -rf "$dir"
  if [ "$has_banner" -ge 1 ]; then ok "$name"; else fail "$name" "no AUTO-GENERATED banner in head"; fi
}

# TestGenSpecsReadme_HandlesFilenameWithSpaces
case_filename_spaces() {
  local name="handles filename with spaces"
  local dir
  dir=$(setup_workdir)
  bash "$GEN" --specs-dir "$dir" --out "$dir/README.md" >/dev/null 2>&1
  local hit
  hit=$(grep -c 'spec-with spaces.md' "$dir/README.md" || true)
  rm -rf "$dir"
  if [ "$hit" -ge 1 ]; then ok "$name"; else fail "$name" "space-bearing filename dropped"; fi
}

# TestGenSpecsReadme_AlphabeticalWithinSection
case_alphabetical_order() {
  local name="alphabetical order within each section"
  local dir
  dir=$(mktemp -d)
  # Three specs, deliberately created in non-alphabetic file-system order.
  printf '# Cee\n' > "$dir/c.md"
  printf '# Bee\n' > "$dir/b.md"
  printf '# Ay\n'  > "$dir/a.md"
  bash "$GEN" --specs-dir "$dir" --out "$dir/README.md" >/dev/null 2>&1
  # Extract spec filenames in order they appear; dedupe by first occurrence
  # so the two refs per row (backticked + link target) collapse.
  local order
  order=$(grep -oE 'a\.md|b\.md|c\.md' "$dir/README.md" | awk '!seen[$0]++' | tr '\n' ' ')
  rm -rf "$dir"
  if [ "$order" = "a.md b.md c.md " ]; then ok "$name"; else fail "$name" "order was: $order"; fi
}

# TestGenSpecsReadme_StaleDetectionFlag
case_stale_detection() {
  # The CI gate: running the generator on a dir where README is up-to-date
  # exits 0; running on a stale README and passing --check exits non-zero.
  local name="--check exits non-zero on stale output"
  local dir
  dir=$(setup_workdir)
  # First generate canonical output.
  bash "$GEN" --specs-dir "$dir" --out "$dir/README.md" >/dev/null 2>&1
  # Corrupt the README so --check should flag it.
  echo "stale junk" >> "$dir/README.md"
  bash "$GEN" --specs-dir "$dir" --out "$dir/README.md" --check >/dev/null 2>&1
  local got=$?
  rm -rf "$dir"
  if [ "$got" -ne 0 ]; then ok "$name"; else fail "$name" "--check passed on stale file"; fi
}

case_deterministic
case_includes_all_specs
case_skips_readme
case_status_groups
case_frontmatter_title_overrides
case_banner_present
case_filename_spaces
case_alphabetical_order
case_stale_detection

echo
if [ "$fails" -gt 0 ]; then
  echo "gen-specs-readme_test: $fails failed, $passes passed"
  for n in "${failed_names[@]}"; do echo "  - $n"; done
  exit 1
fi
echo "gen-specs-readme_test: all $passes case(s) passed"
