#!/usr/bin/env bash
# gen-specs-readme.sh - regenerate docs/engineer/specs/README.md from the
# filesystem so parallel spec PRs stop cascade-rebasing the same anchor.
#
# Why this script exists: every spec PR previously appended one row to the
# index. With 6+ concurrent spec PRs the bottom of README.md became a
# DIRTY-merge magnet (8+ PRs hit it on 2026-06-02). Auto-generating the
# index from the spec files themselves moves the source-of-truth into each
# spec, eliminates the shared anchor, and makes the index a derived
# artifact a CI gate can verify byte-for-byte.
#
# Input: every *.md file in --specs-dir (default docs/engineer/specs/),
# minus README.md. Each spec may carry an optional YAML-ish frontmatter:
#   ---
#   title: One-line title to render in the index (overrides H1).
#   status: active | shipped | archived  (default: active)
#   summary: One-line description shown next to the link.
#   ---
# If no frontmatter, the first H1 line becomes the title and the summary
# is empty. status defaults to active.
#
# Output: deterministic README.md. Same FS state -> byte-identical bytes.
#
# Flags:
#   --specs-dir <dir>   directory containing the spec corpus
#   --out <file>        output path (default: <specs-dir>/README.md)
#   --check             do not write; exit 1 if file would change

set -euo pipefail

specs_dir="docs/engineer/specs"
out=""
check=0
while [ $# -gt 0 ]; do
  case "$1" in
    --specs-dir) specs_dir="$2"; shift 2 ;;
    --out)       out="$2";       shift 2 ;;
    --check)     check=1;        shift   ;;
    -h|--help)
      sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "gen-specs-readme: unknown flag: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$out" ]; then
  out="$specs_dir/README.md"
fi

if [ ! -d "$specs_dir" ]; then
  echo "gen-specs-readme: specs dir does not exist: $specs_dir" >&2
  exit 2
fi

# parse_spec <path>
#   Emits TAB-separated: <status>\t<filename>\t<title>\t<summary>
#   - status defaults to "active"
#   - title falls back to first H1 ("# foo") -> "foo"
#   - title final fallback: bare filename without .md
parse_spec() {
  local path="$1"
  local base
  base=$(basename -- "$path")
  python3 - "$path" "$base" <<'PY'
import re, sys
path, base = sys.argv[1], sys.argv[2]
with open(path, "r", encoding="utf-8", errors="replace") as fh:
    lines = fh.read().splitlines()

title = ""
status = "active"
summary = ""

# YAML-ish frontmatter: opening '---' on line 1, closing '---' before any
# content. Keys we recognize: title, status, summary. Unknown keys ignored.
if lines and lines[0].strip() == "---":
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is not None:
        for raw in lines[1:end]:
            if ":" not in raw:
                continue
            k, _, v = raw.partition(":")
            k = k.strip().lower()
            v = v.strip()
            # Strip matching surrounding quotes.
            if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
                v = v[1:-1]
            if k == "title":
                title = v
            elif k == "status":
                status = v.lower()
            elif k in ("summary", "description"):
                summary = v
        body = lines[end + 1:]
    else:
        body = lines
else:
    body = lines

# H1 fallback when frontmatter didn't supply a title.
if not title:
    for ln in body:
        if ln.startswith("# "):
            title = ln[2:].strip()
            break

if not title:
    # Filename without extension as last resort.
    title = re.sub(r"\.md$", "", base)

if status not in ("active", "shipped", "archived"):
    status = "active"

# Single-line guarantees — TAB is the field separator.
title = title.replace("\t", " ").replace("\n", " ").strip()
summary = summary.replace("\t", " ").replace("\n", " ").strip()
status = status.replace("\t", " ").strip()

print(f"{status}\t{base}\t{title}\t{summary}")
PY
}

# Render the entire README content to stdout.
render() {
  cat <<'BANNER'
<!-- AUTO-GENERATED by scripts/gen-specs-readme.sh — DO NOT EDIT BY HAND.
     To change a row: edit the corresponding spec's frontmatter (title,
     status, summary). To change preamble or trailing prose: edit the
     STATIC_* heredocs in scripts/gen-specs-readme.sh. -->

# Engineer specs

Locked design for the ACTIVE or NEXT wave. One spec per wedge. Specs here are the canonical design that implementer subagents follow; deviations require re-spawning the design subagent (per `memory/feedback_spec_pattern_authority`).

Each row is generated from the spec's own frontmatter (`title`, `status`, `summary`) — no manual edits to this README. Add a new spec by dropping the file into this directory and running `make specs-index`.

BANNER

  # Gather rows; sort by (section-order, filename) so output is deterministic.
  # POSIX `sort` honors LC_ALL=C; pin it.
  local rows
  rows=$(
    shopt -s nullglob
    for f in "$specs_dir"/*.md; do
      base=$(basename -- "$f")
      [ "$base" = "README.md" ] && continue
      parse_spec "$f"
    done | LC_ALL=C sort -t $'\t' -k1,1 -k2,2
  )

  emit_section() {
    local label="$1" want_status="$2" intro="$3"
    local section_rows
    section_rows=$(printf '%s\n' "$rows" | awk -F'\t' -v s="$want_status" '$1==s')
    echo "## $label"
    echo
    if [ -z "$section_rows" ]; then
      echo "_None._"
      echo
      return
    fi
    [ -n "$intro" ] && { echo "$intro"; echo; }
    # Within a section, sort by filename ascending (sort already did so).
    while IFS=$'\t' read -r status file title summary; do
      [ -z "$file" ] && continue
      if [ -n "$summary" ]; then
        printf -- '- [`%s`](%s) — %s — %s\n' "$file" "$file" "$title" "$summary"
      else
        printf -- '- [`%s`](%s) — %s\n' "$file" "$file" "$title"
      fi
    done <<< "$section_rows"
    echo
  }

  emit_section "Active / next-wave specs" "active" ""
  emit_section "Shipped" "shipped" "Specs whose implementation has landed; retained for archaeology."
  emit_section "Archived" "archived" "Superseded or abandoned designs; retained so links from older PRs still resolve."

  cat <<'TRAILER'
## Dependency graph

```
              W6 (OTel)
                 |
             substrate           (substrate ships after W6 T1+T2+T5)
                 |
        +--------+--------+
        |                 |
        W7              [adapters]    (W7 and adapters are orthogonal)
        |
        W8 (OPA RBAC + tenant_id)
        |
        W9 (replay + diff)
```

`W6 -> substrate -> W7 + W8 -> W9`. Adapters (P3.8) ship orthogonally on first hosted-backend customer ask. Substrate is load-bearing for every later wedge that needs the events log; W7's Authorizer interface seam is the W8 plug-in point with no W7 re-architecture; W9 reads W6's events shape, renders through W7's UI, and scopes per W8's `tenant_id` column.

## What goes here

- Locked design for the ACTIVE or NEXT wave.
- One spec per wedge; each ends with a B/A/A+ grade rubric.
- Schema, migration, reducer, interface boundaries, file layout, parallel-dispatch plan.

## What does NOT go here

- Strategic vision (goes in `../briefs/`).
- Accepted decisions for shipped milestones (goes in `../../rfcs/`).
- Per-iteration drafts, plans, dispatch prompts, working reviews, superseded specs (stay under `docs/superpowers/`, gitignored, one-shot).

Per-iteration scratch lives in `docs/superpowers/` and is gitignored on purpose; the final-state, tracked design lives here.

## Related RFCs (shipped milestone decisions)

- [`../../rfcs/0001-mvp-1-program-publish.md`](../../rfcs/0001-mvp-1-program-publish.md) — MVP-1 program publish via sqlite, not SpecAdapter.
- [`../../rfcs/0002-mvp-2-conditional-dag.md`](../../rfcs/0002-mvp-2-conditional-dag.md) — MVP-2 W1 outcome-conditional DAG (CEL edges + journal).
- [`../../rfcs/0003-mvp-2-approval-gates.md`](../../rfcs/0003-mvp-2-approval-gates.md) — MVP-2 approval gates (HMAC token + reaper + fold).
TRAILER
}

new_content=$(render)

if [ "$check" -eq 1 ]; then
  if [ ! -f "$out" ]; then
    echo "gen-specs-readme: --check failed; $out does not exist" >&2
    exit 1
  fi
  current=$(cat "$out")
  if [ "$current" != "$new_content" ]; then
    echo "gen-specs-readme: --check failed; $out is stale. Run 'make specs-index' and commit." >&2
    diff -u <(printf '%s\n' "$current") <(printf '%s\n' "$new_content") | sed 's/^/  /' >&2 || true
    exit 1
  fi
  echo "gen-specs-readme: $out is up to date"
  exit 0
fi

printf '%s\n' "$new_content" > "$out"
echo "gen-specs-readme: wrote $out"
